/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ShieldCapPropertyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_OWNERSHIP_BPS"
      | "balanceOfProperty"
      | "buySecondaryListing"
      | "cancelSecondaryListing"
      | "claimDividend"
      | "confidentialProtocolId"
      | "createProperty"
      | "createSecondaryListing"
      | "distributeDividend"
      | "dividendOf"
      | "dividendRound"
      | "getProperty"
      | "getSecondaryListing"
      | "investorCount"
      | "maxSharesForProperty"
      | "nextListingId"
      | "nextPropertyId"
      | "owner"
      | "paymentToken"
      | "purchaseShares"
      | "renounceOwnership"
      | "totalSharesAllocated"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfidentialTransfer"
      | "DividendClaimed"
      | "DividendDistributed"
      | "OwnershipTransferred"
      | "PropertyListed"
      | "SecondaryListingCancelled"
      | "SecondaryListingCreated"
      | "SecondaryListingDepleted"
      | "SecondaryListingFilled"
      | "SharesPurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_OWNERSHIP_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfProperty",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buySecondaryListing",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSecondaryListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDividend",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createProperty",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSecondaryListing",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeDividend",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dividendOf",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dividendRound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProperty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecondaryListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investorCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxSharesForProperty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextListingId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextPropertyId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseShares",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSharesAllocated",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_OWNERSHIP_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buySecondaryListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSecondaryListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSecondaryListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dividendOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dividendRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecondaryListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSharesForProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextListingId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPropertyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSharesAllocated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ConfidentialTransferEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendClaimedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    investor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    investor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    investor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendDistributedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    round: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    round: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    round: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyListedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    name: string,
    totalShares: BigNumberish,
    pricePerShare: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    name: string,
    totalShares: bigint,
    pricePerShare: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    name: string;
    totalShares: bigint;
    pricePerShare: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecondaryListingCancelledEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    propertyId: BigNumberish,
    seller: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    propertyId: bigint,
    seller: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    propertyId: bigint;
    seller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecondaryListingCreatedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    propertyId: BigNumberish,
    seller: AddressLike,
    pricePerShare: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    propertyId: bigint,
    seller: string,
    pricePerShare: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    propertyId: bigint;
    seller: string;
    pricePerShare: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecondaryListingDepletedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    propertyId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    propertyId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    propertyId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecondaryListingFilledEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    propertyId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    propertyId: bigint,
    buyer: string,
    seller: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    propertyId: bigint;
    buyer: string;
    seller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesPurchasedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    buyer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    buyer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    buyer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShieldCapProperty extends BaseContract {
  connect(runner?: ContractRunner | null): ShieldCapProperty;
  waitForDeployment(): Promise<this>;

  interface: ShieldCapPropertyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_OWNERSHIP_BPS: TypedContractMethod<[], [bigint], "view">;

  balanceOfProperty: TypedContractMethod<
    [propertyId: BigNumberish, account: AddressLike],
    [string],
    "view"
  >;

  buySecondaryListing: TypedContractMethod<
    [
      listingId: BigNumberish,
      encryptedShareAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  cancelSecondaryListing: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimDividend: TypedContractMethod<
    [propertyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createProperty: TypedContractMethod<
    [
      name: string,
      location: string,
      imageUri: string,
      description: string,
      valueUsd: BigNumberish,
      totalShares: BigNumberish,
      pricePerShare: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createSecondaryListing: TypedContractMethod<
    [
      propertyId: BigNumberish,
      pricePerShare: BigNumberish,
      encryptedShareAmount: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  distributeDividend: TypedContractMethod<
    [
      propertyId: BigNumberish,
      encryptedRevenue: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  dividendOf: TypedContractMethod<
    [propertyId: BigNumberish, account: AddressLike],
    [string],
    "view"
  >;

  dividendRound: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getProperty: TypedContractMethod<
    [propertyId: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        location: string;
        imageUri: string;
        description: string;
        valueUsd: bigint;
        totalShares: bigint;
        pricePerShare: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getSecondaryListing: TypedContractMethod<
    [listingId: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        propertyId: bigint;
        seller: string;
        sharesRemaining: string;
        pricePerShare: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  investorCount: TypedContractMethod<
    [propertyId: BigNumberish],
    [bigint],
    "view"
  >;

  maxSharesForProperty: TypedContractMethod<
    [propertyId: BigNumberish],
    [bigint],
    "view"
  >;

  nextListingId: TypedContractMethod<[], [bigint], "view">;

  nextPropertyId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  purchaseShares: TypedContractMethod<
    [
      propertyId: BigNumberish,
      encryptedShareAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalSharesAllocated: TypedContractMethod<
    [propertyId: BigNumberish],
    [string],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_OWNERSHIP_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfProperty"
  ): TypedContractMethod<
    [propertyId: BigNumberish, account: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "buySecondaryListing"
  ): TypedContractMethod<
    [
      listingId: BigNumberish,
      encryptedShareAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelSecondaryListing"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDividend"
  ): TypedContractMethod<[propertyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createProperty"
  ): TypedContractMethod<
    [
      name: string,
      location: string,
      imageUri: string,
      description: string,
      valueUsd: BigNumberish,
      totalShares: BigNumberish,
      pricePerShare: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSecondaryListing"
  ): TypedContractMethod<
    [
      propertyId: BigNumberish,
      pricePerShare: BigNumberish,
      encryptedShareAmount: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeDividend"
  ): TypedContractMethod<
    [
      propertyId: BigNumberish,
      encryptedRevenue: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dividendOf"
  ): TypedContractMethod<
    [propertyId: BigNumberish, account: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "dividendRound"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProperty"
  ): TypedContractMethod<
    [propertyId: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        location: string;
        imageUri: string;
        description: string;
        valueUsd: bigint;
        totalShares: bigint;
        pricePerShare: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSecondaryListing"
  ): TypedContractMethod<
    [listingId: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        propertyId: bigint;
        seller: string;
        sharesRemaining: string;
        pricePerShare: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "investorCount"
  ): TypedContractMethod<[propertyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxSharesForProperty"
  ): TypedContractMethod<[propertyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextListingId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextPropertyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseShares"
  ): TypedContractMethod<
    [
      propertyId: BigNumberish,
      encryptedShareAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalSharesAllocated"
  ): TypedContractMethod<[propertyId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ConfidentialTransfer"
  ): TypedContractEvent<
    ConfidentialTransferEvent.InputTuple,
    ConfidentialTransferEvent.OutputTuple,
    ConfidentialTransferEvent.OutputObject
  >;
  getEvent(
    key: "DividendClaimed"
  ): TypedContractEvent<
    DividendClaimedEvent.InputTuple,
    DividendClaimedEvent.OutputTuple,
    DividendClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DividendDistributed"
  ): TypedContractEvent<
    DividendDistributedEvent.InputTuple,
    DividendDistributedEvent.OutputTuple,
    DividendDistributedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyListed"
  ): TypedContractEvent<
    PropertyListedEvent.InputTuple,
    PropertyListedEvent.OutputTuple,
    PropertyListedEvent.OutputObject
  >;
  getEvent(
    key: "SecondaryListingCancelled"
  ): TypedContractEvent<
    SecondaryListingCancelledEvent.InputTuple,
    SecondaryListingCancelledEvent.OutputTuple,
    SecondaryListingCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SecondaryListingCreated"
  ): TypedContractEvent<
    SecondaryListingCreatedEvent.InputTuple,
    SecondaryListingCreatedEvent.OutputTuple,
    SecondaryListingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SecondaryListingDepleted"
  ): TypedContractEvent<
    SecondaryListingDepletedEvent.InputTuple,
    SecondaryListingDepletedEvent.OutputTuple,
    SecondaryListingDepletedEvent.OutputObject
  >;
  getEvent(
    key: "SecondaryListingFilled"
  ): TypedContractEvent<
    SecondaryListingFilledEvent.InputTuple,
    SecondaryListingFilledEvent.OutputTuple,
    SecondaryListingFilledEvent.OutputObject
  >;
  getEvent(
    key: "SharesPurchased"
  ): TypedContractEvent<
    SharesPurchasedEvent.InputTuple,
    SharesPurchasedEvent.OutputTuple,
    SharesPurchasedEvent.OutputObject
  >;

  filters: {
    "ConfidentialTransfer(uint256,address,address,uint256)": TypedContractEvent<
      ConfidentialTransferEvent.InputTuple,
      ConfidentialTransferEvent.OutputTuple,
      ConfidentialTransferEvent.OutputObject
    >;
    ConfidentialTransfer: TypedContractEvent<
      ConfidentialTransferEvent.InputTuple,
      ConfidentialTransferEvent.OutputTuple,
      ConfidentialTransferEvent.OutputObject
    >;

    "DividendClaimed(uint256,address,uint256)": TypedContractEvent<
      DividendClaimedEvent.InputTuple,
      DividendClaimedEvent.OutputTuple,
      DividendClaimedEvent.OutputObject
    >;
    DividendClaimed: TypedContractEvent<
      DividendClaimedEvent.InputTuple,
      DividendClaimedEvent.OutputTuple,
      DividendClaimedEvent.OutputObject
    >;

    "DividendDistributed(uint256,uint256,uint256)": TypedContractEvent<
      DividendDistributedEvent.InputTuple,
      DividendDistributedEvent.OutputTuple,
      DividendDistributedEvent.OutputObject
    >;
    DividendDistributed: TypedContractEvent<
      DividendDistributedEvent.InputTuple,
      DividendDistributedEvent.OutputTuple,
      DividendDistributedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PropertyListed(uint256,string,uint256,uint256,uint256)": TypedContractEvent<
      PropertyListedEvent.InputTuple,
      PropertyListedEvent.OutputTuple,
      PropertyListedEvent.OutputObject
    >;
    PropertyListed: TypedContractEvent<
      PropertyListedEvent.InputTuple,
      PropertyListedEvent.OutputTuple,
      PropertyListedEvent.OutputObject
    >;

    "SecondaryListingCancelled(uint256,uint256,address,uint256)": TypedContractEvent<
      SecondaryListingCancelledEvent.InputTuple,
      SecondaryListingCancelledEvent.OutputTuple,
      SecondaryListingCancelledEvent.OutputObject
    >;
    SecondaryListingCancelled: TypedContractEvent<
      SecondaryListingCancelledEvent.InputTuple,
      SecondaryListingCancelledEvent.OutputTuple,
      SecondaryListingCancelledEvent.OutputObject
    >;

    "SecondaryListingCreated(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      SecondaryListingCreatedEvent.InputTuple,
      SecondaryListingCreatedEvent.OutputTuple,
      SecondaryListingCreatedEvent.OutputObject
    >;
    SecondaryListingCreated: TypedContractEvent<
      SecondaryListingCreatedEvent.InputTuple,
      SecondaryListingCreatedEvent.OutputTuple,
      SecondaryListingCreatedEvent.OutputObject
    >;

    "SecondaryListingDepleted(uint256,uint256,uint256)": TypedContractEvent<
      SecondaryListingDepletedEvent.InputTuple,
      SecondaryListingDepletedEvent.OutputTuple,
      SecondaryListingDepletedEvent.OutputObject
    >;
    SecondaryListingDepleted: TypedContractEvent<
      SecondaryListingDepletedEvent.InputTuple,
      SecondaryListingDepletedEvent.OutputTuple,
      SecondaryListingDepletedEvent.OutputObject
    >;

    "SecondaryListingFilled(uint256,uint256,address,address,uint256)": TypedContractEvent<
      SecondaryListingFilledEvent.InputTuple,
      SecondaryListingFilledEvent.OutputTuple,
      SecondaryListingFilledEvent.OutputObject
    >;
    SecondaryListingFilled: TypedContractEvent<
      SecondaryListingFilledEvent.InputTuple,
      SecondaryListingFilledEvent.OutputTuple,
      SecondaryListingFilledEvent.OutputObject
    >;

    "SharesPurchased(uint256,address,uint256)": TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;
    SharesPurchased: TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;
  };
}
